spring.application.name=PanVerification

spring.datasource.url=jdbc:mysql://localhost:3306/pan_verification_db
spring.datasource.username=root
spring.datasource.password=mohit123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
opv.pfx-file=certs/VerasysSubCA2022.pfx
opv.pfx-password=abc1234

protean.user-id=V0024301
protean.version=4

protean.uat-url=https://121.240.36.237/TIN/PanInquiryAPIBackEnd

certificate.path=certificates/protean.p12
certificate.password=abc1234

logging.level.root=INFO

logging.level.com.verify.panverification=DEBUG